### ISSUE TITLE
Support cyclic dependencies

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/truffle-flattener#14]
Currently `truffle-flattener` doesn't support cyclic dependencies. It just fails when such dependencies are found. This happens because it just concats the graph of dependencies in the right (any topological) order.

An alternative to this is to actually parse the files and merge their AST. This way declarations can be written in order in the output.

This has two drawbacks:
1.  It's far more complex, but anyone with a basic understanding of parsing or willing to learn about it can tackle it.
2.  The 1-to-1 relationship between contiguos sections of the output and dependencies is lost, which makes it less useful for debugging.

I'm not really interested in implementing this (I think having cyclic dependencies should be avoided), but I can provide guidance for anyone who wants to do it.

The only condition for merging a PR for this is that it should make its best effort to only alter the output for the cyclic parts of the dependencies graph, avoiding drawback (2) as much as possible.

**Comment by marsrobertson** [comment]
AST = abstract syntaxt tree

I've just wanted to use `truffle-flattener`, encountered an issue: https://github.com/kleros/kleros-interaction/issues/249#issue-432951431

Would be nice to get it working but outside of my area of expertise.

**Comment by Pet3ris** [comment]
+1, would be awesome to support this, currently an issue while trying to flatten `dydx` contracts!

**Comment by SharjeelSafdar** [comment]
It would be a great feature. In case one is using an external library, one can't avoid circular dependencies. E.g. there are circular dependencies in @openzeppelin.

**Comment by mrx23dot** [comment]
How does solc solve this? 
It also generates one binary file from multiple .sol ones.

Here is an example contract that fails  0x1d681d76ce96e4d70a88a00ebbcfc1e47808d0b8
[temp.zip](https://github.com/nomiclabs/truffle-flattener/files/7978575/temp.zip)

`Error: ENOENT: no such file or directory, open 'c:/tmp/flt/build/temp/action_pipeline_interfaces/IGelatoInAndOutFlowAction.sol'`

**Comment by alcuadrado** [comment]
We have no intention of adding support for cyclic dependencies.

In general, you should avoid flattening. In particular, flattening to verify a contract is a risky move, as it can lead to different compilation outputs. Use `hardhat-etherscan` or a similar system instead.
