### ISSUE TITLE
Specify imported library version in comments

### ISSUE THREAD

**Issue by dmdque** [NomicFoundation/truffle-flattener#19]
It would be nice if `truffle-flattener` added the package version of the imported library in the comments of the output file.

For example:

    // File: zeppelin-solidity/contracts/ownership/Ownable.sol Package: zeppelin-solidity@v1.7.0

**Comment by alcuadrado** [comment]
Great idea! 

It can be implemented in a quick but dirty way by getting the version from each dependency's `package.json` when writing that message.

I'm afraid I won't have time for implementing it for a few days, but if someone wants to do it I can provide some guidance.

**Comment by dmdque** [comment]
That sounds like a good solution to me. How else would you do it such that it isn't "quick and dirty?"

**Comment by alcuadrado** [comment]
Maybe truffle resolver gives information about the library. Note that truffle supports both npm and ethpm, and that idea only works for the former.

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
