### ISSUE TITLE
Include --output in the docs

### ISSUE THREAD

**Issue by kiliw** [NomicFoundation/truffle-flattener#39]
Hello all together,

we are using your *truffle-flattener* and so far it works great. We saw in the [code](https://github.com/nomiclabs/truffle-flattener/pull/27) that there is the `--output` option to suppress the yarn comments in the flattend .sol files.

Maybe you guys can include this option in your docs? Would be better I think if one can directly get this from the README :)

Thank your very much.
Best regards.

**Comment by dobpp** [comment]
Is this package maintained?

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
