### ISSUE TITLE
duplicate interfaces produced on Windows

### ISSUE THREAD

**Issue by dkent600** [NomicFoundation/truffle-flattener#40]
When I flatten a certain contract on Windows I end up with duplicate declarations of `interface IERC20`.  In a Bash shell, I don't.  I'm attaching the contract (Avatar), and the good and bad output.

[flattened-bad.txt](https://github.com/nomiclabs/truffle-flattener/files/2962328/flattened-bad.txt)
[flattened-good.txt](https://github.com/nomiclabs/truffle-flattener/files/2962329/flattened-good.txt)
[Avatar.sol.txt](https://github.com/nomiclabs/truffle-flattener/files/2962334/Avatar.sol.txt)

**Comment by dkent600** [comment]
The Avatar contract is from [here](https://github.com/daostack/arc/blob/0.0.1-rc.9/contracts/controller/Avatar.sol).

**Comment by dkent600** [comment]
I assumed too much.  The difference is not between Windows and Bash.  For me it is actually between the two cases:  1) running in a project that is at the root of an NPM project, and 2) running in a project that is under node_modules of a project.  The latter case is the failing one.

**Comment by alcuadrado** [comment]
Hey @dkent600 ! Thanks for digging deeper into this issue. I'll try to get into this later this week.

Who are you running `truffle-flattener`?

**Comment by alcuadrado** [comment]
Oops. I meant how 😅

**Comment by dkent600** [comment]
I intend to use it in a nodejs script, but one can reproduce this by running `truffle-flattener [filename.sol]` in either a bash or windows shell.

**Comment by dkent600** [comment]
@alcuadrado  Update:  I can no longer figure out how I ever got truffle-flattener to work in Windows.  In Bash, it works as long as openzeppelin-solidity is installed in the folder in which truffle-flattener is being run, even if the folder is itself a package installed under node_modules of another folder.

I'm guessing the problem with Windows is related to backslashes, '\' versus '/'.

**Comment by alexanderm39** [comment]
I have the same issue with version 1.3.0.
1.2.9 with [this fix](https://github.com/nomiclabs/truffle-flattener/pull/33) works Ok for me.

**Comment by alexanderm39** [comment]
Seems, the issue came with the 'resolver-engine'.
[a593ed2] commit is still Ok.

**Comment by alcuadrado** [comment]
Hi @alexanderm39, thanks for taking the time to try that.

There are two issues being reported here:
1. There are cases where a file is imported multiple times. 
2. `resolver-engine` fails on windows.

I'm working on (1). Do you mind reporting (2) in https://github.com/Crypto-Punkers/resolver-engine ?

**Comment by dkent600** [comment]
@alcuadrado

> There are two issues being reported here

I think dup interfaces is the symptom of the failure of resolver-engine.

**Comment by alcuadrado** [comment]
I found at least an independent case of that issue when running I'm case insensitive file systems. I'll fix that for now.

**Comment by pash7ka** [comment]
This happens for me when a contract is imported within my project via a reference to node module, like
```
import "@openzeppelin/contracts-ethereum-package/contracts/GSN/Context.sol";
```
and second time from a contract inside that module like
```
import "../../GSN/Context.sol";
```
So i believe pr #33 will not fix the issue in my case.

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._

**Comment by SoftwareAngels** [comment]
Still a bug.
