### ISSUE TITLE
add command line option to specify the truffle config file to be used

### ISSUE THREAD

**Issue by shunp** [NomicFoundation/truffle-flattener#50]
This is an enhancement request to add a command-line option to specify the truffle config file to be used on the compilation.

I would like to add like the below in the main function.

```javascript
  let rootIndex = args.indexOf("--root");
```

[Example]
```
truffle-flattener contracts/XXX.sol --output build/contracts/FlattenerXXX.sol --dir ./subdir
```
```
/rootdir
    |--subdir
    |       |--/contracts
    |       |--/build
    |       |--truffle-config.js
    |--/nodemodules
    |--package.json
```

[Related]
https://github.com/trufflesuite/truffle/issues/1879

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
