### ISSUE TITLE
Solidity 6 'immutable' breaks parser

### ISSUE THREAD

**Issue by dmihal** [NomicFoundation/truffle-flattener#53]
When a contract includes an `immutable` storage variable, the parser fails.

Error:
`Error: Could not parse MyContract.sol for extracting its imports: ParserError: mismatched input 'private' expecting {';', '='} (17:20)`

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
