### ISSUE TITLE
Error: None of the sub-resolvers resolved "@openzeppelin/contracts/access/Ownable.sol" location.

### ISSUE THREAD

**Issue by naszam** [NomicFoundation/truffle-flattener#54]
Hi, 
I'm trying to use truffle-flattener v1.4.4 to flatten my truffle project contracts, but I'm getting the following error:
```
Error: None of the sub-resolvers resolved "@openzeppelin/contracts/access/Ownable.sol" location.
```
when trying the following:

```
$ truffle-flattener MyContract.sol > FlattenMyContract.sol
```

Using the following dependences:
Ubuntu 18.04
npm v13.13.0
truffle v5.1.25
solc v0.6.7

**Comment by frangio** [comment]
Hi @naszam. I wasn't able to reproduce your issue.

Does your contract compile successfully using `truffle compile`? What version of `@openzeppelin/contracts` are you using?

**Comment by naszam** [comment]
Hi @frangio.

Yep! 
OpenZeppelin v3.0

**Comment by frangio** [comment]
If you want to upload your project somewhere I can take a look, otherwise I don't know what could be causing this.

**Comment by naszam** [comment]
I've fixed it!
So, the issue was that I was using truffle-flattener as global dependency and not local.
Setting both OpenZeppelin and truffle-flattener local, I managed to get it working.
Thanks!
