### ISSUE TITLE
Will support hardhat?

### ISSUE THREAD

**Issue by roronoa-jeff** [NomicFoundation/truffle-flattener#65]
Will support hardhat?

Error: 
      Truffle Flattener must be run inside a Truffle or Buidler project:
      truffle.js, truffle-config.js, buidler.config.js, nor buidler.config.ts found

**Comment by alcuadrado** [comment]
Sure. Would you send a PR? It should look really similar to this: https://github.com/nomiclabs/truffle-flattener/commit/e1f253871a456283bc9f57c70dde69b91f86a8ac

**Comment by wenshenjun** [comment]
@alcuadrado  Had send a PR. please check.

**Comment by vporton** [comment]
> @alcuadrado Had send a PR. please check.

https://github.com/nomiclabs/truffle-flattener/pull/66 - this one.

**Comment by zidzid1234** [comment]
Hi, has this been fixed? I am still getting this error. Please help. Thank you!

**Comment by alcuadrado** [comment]
Hardhat has a built-in, much more advanced, flattening system.
