### ISSUE TITLE
Crashes when pathname includes spaces.

### ISSUE THREAD

**Issue by zimmah** [NomicFoundation/truffle-flattener#67]
Whenever the pathname includes spaces, the spaces are replaced by '%20', which, at least in powershell, leads the program to halt and return an error saying it can't open the file.

Powershell handles spaces in paths by putting quotes around it, like a string.

for example:

c:\'Program Files'\something\helloWorld.sol

**Comment by TCGV** [comment]
Here's a quick trick that I used to overcome this issue when running from powershell:

Go the the `\npm\node_modules\truffle-flattener\index.js` file and add a call to replace all occurencies of `%20` by blank spaces:

![image](https://user-images.githubusercontent.com/2445889/139918544-2f5235e5-17ef-4f1d-b36c-a386ae12f8cd.png)

Not sure what the impact of that would be in linux boxes.

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
