### ISSUE TITLE
Could not parse smart contract with "unchecked block" syntax

### ISSUE THREAD

**Issue by edilsalvador** [NomicFoundation/truffle-flattener#77]
When I flatten a certain smart contract that uses openzeppelin's SafeMath library I'm getting this error:
`Error: Could not parse @openzeppelin/contracts/utils/math/SafeMath.sol for extracting its imports: ParserError: missing ';' at '{'`

Upon investigation, flattening fails when encountering an `unchecked block`.
`unchecked block` is a valid solidity syntax introduced since `0.8.0`, check reference [here](https://docs.soliditylang.org/en/v0.8.0/control-structures.html#checked-or-unchecked-arithmetic).

Sample code to reproduce the error:
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

library SafeMath {
    . . .
    function tryDiv(uint256 a, uint256 b) internal pure returns (bool, uint256) {
        unchecked {
            if (b == 0) return (false, 0);
            return (true, a / b);
        }
    }
   . . .
}
```

**Comment by sdelvalle57** [comment]
Did you get to solve this?

**Comment by MrClottom** [comment]
Having the same issue here.

**Comment by kabl** [comment]
same issue here...

**Comment by AymericNoel** [comment]
Same here...

**Comment by fforbeck** [comment]
Same issue

**Comment by jplew** [comment]
The problem is due to an outdated version of @solidity-parser/parser. See this PR: https://github.com/nomiclabs/truffle-flattener/pull/81

If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.

**Comment by fedeb95** [comment]
> 
> 
> The problem is due to an outdated version of @solidity-parser/parser. See this PR: #81
> 
> If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.

you can also npm package, then npm install the artifact and still use truffle-flattener system wide :) in case you got scripts depending on it

**Comment by AymericNoel** [comment]
> > The problem is due to an outdated version of @solidity-parser/parser. See this PR: #81
> > If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.
> 
> you can also npm package, then npm install the artifact and still use truffle-flattener system wide :) in case you got scripts depending on it

You can also do `npm i https://github.com/jplew/truffle-flattener` that will replace current `truffle-flattener` package with branch linked in PR #81. It works fine

**Comment by edilsalvador** [comment]
Confirming that PR #80 / #81 fix the issue. Thanks @fedeb95 & @jplew 👍

**Comment by ngduc** [comment]
The parser lib (dependency) is outdated. Those PRs need to be merged to upgrade it.
This one should work https://github.com/ngduc/flatten-sol

**Comment by harsh-im** [comment]
> > > The problem is due to an outdated version of @solidity-parser/parser. See this PR: #81
> > > If you can't wait for the maintainers to rerelease the package, just fork mine, npm install, then run `./index.js MyContract.sol` instead of `truffle-flattener MyContract.sol`.
> > 
> > 
> > you can also npm package, then npm install the artifact and still use truffle-flattener system wide :) in case you got scripts depending on it
> 
> You can also do `npm i https://github.com/jplew/truffle-flattener` that will replace current `truffle-flattener` package with branch linked in PR #81. It works fine

This is not working as I am getting the same error

**Comment by cheffNFT** [comment]
still having the same situation here

**Comment by Joachim-Lebrun** [comment]
thanks for solving the issue @jplew 😊

**Comment by baoduy** [comment]
I still got the same issue today. I'm using the truffle-flattener **1.5.0** now

**Comment by mrx23dot** [comment]
only this one worked for me:
`sudo npm install "https://github.com/fedeb95/truffle-flattener.git#master" -g --save`

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._

**Comment by fedeb95** [comment]
so does it work now for unchecked block? was it solved?

**Comment by alcuadrado** [comment]
It should be.
