### ISSUE TITLE
How to export the flattened version generated by truffle-flattener?

### ISSUE THREAD

**Issue by dnguyencode** [NomicFoundation/truffle-flattener#82]
Hi, it seems that this script only generate the flattened version and print them into the terminal. Is there a way to export the flattened into a file? If not is there a point in generating the flattened version and print them into the terminal?

**Comment by themotu** [comment]
truffle-flattener mycontract.sol > mycontract-flattened.sol

**Comment by mrx23dot** [comment]
The size of the pipe is limited, so it would be wise to have --output file
https://stackoverflow.com/questions/6977561/pipe-vs-temporary-file

Also some contracts have unicode, not sure what happens with those.
