### ISSUE TITLE
npx github:fedeb95/truffle-flattener is error!!!

### ISSUE THREAD

**Issue by dengdeng95** [NomicFoundation/truffle-flattener#84]
npm ERR! Error while executing:
npm ERR! X:\XX\xxx\bin\git.EXE ls-remote -h -t ssh://git@github.com/fedeb95/truffle-flattener.git
npm ERR!
npm ERR! ssh: Could not resolve hostname github.com: Name or service not known
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     X:\npm-cache\_logs\2021-11-22T02_46_24_545Z-debug.log

**Comment by mrx23dot** [comment]
sudo npm install "https://github.com/fedeb95/truffle-flattener.git#master" -g --save

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
