### ISSUE TITLE
Add output file option

### ISSUE THREAD

**Issue by mrx23dot** [NomicFoundation/truffle-flattener#91]
The size of the pipe is limited, so it would be wise to have` --output file`
https://stackoverflow.com/questions/6977561/pipe-vs-temporary-file

Also some contracts have unicode, not sure what happens with those.

**Comment by alcuadrado** [comment]
Unicode contracts should be ok, but the limited size is interesting.

Would you send a PR adding this option?

**Comment by mrx23dot** [comment]
wait, is this implemented already?

```
    let outputFileIndex = args.indexOf("--output");
    let outputFilePath;

    if (outputFileIndex >= 0) {
        outputFilePath = args[outputFileIndex + 1];

        if (!outputFilePath) {
            console.warn("you havn't provided output file path, ignoring. Usage: truffle-flattener <files> --output <output file path>");
        }
```

**Comment by mrx23dot** [comment]
It works, help text could use update:
`Usage: truffle-flattener <files>`
